#!/bin/bash

# Auto-Build Environment Setup
# Spec: 007-pagination — Infinite Scroll Redesign
# Generated by Planner Agent (Session 1)

set -e

echo "========================================"
echo "VoiceNotes – Pagination Spec Dev Server"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

wait_for_port() {
  local port=$1
  local name=$2
  local max=30
  local count=0

  echo "Waiting for $name on port $port..."
  while ! nc -z localhost $port 2>/dev/null; do
    count=$((count + 1))
    if [ $count -ge $max ]; then
      echo -e "${RED}$name failed to start on port $port${NC}"
      return 1
    fi
    sleep 1
  done
  echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# Option A: Firebase Emulator (preferred)
# ============================================
# Uncomment the section below if firebase-tools is installed:
#
# echo "Starting Firebase emulators..."
# firebase emulators:start --only hosting &
# wait_for_port 5000 "Firebase Hosting Emulator"

# ============================================
# Option B: Plain static server (fallback)
# ============================================
echo -e "${YELLOW}Starting static server on port 5000...${NC}"
echo "(Note: Firestore will use live Firebase, not emulator)"

# Check if npx/serve is available
if command -v npx &>/dev/null; then
  npx serve public -p 5000 &
  wait_for_port 5000 "Static Server (npx serve)"
else
  echo -e "${RED}npx not found. Please install Node.js or run: firebase emulators:start${NC}"
  exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Dev Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:5000/app.html"
echo ""
echo "Files being modified in spec 007:"
echo "  public/css/style.css   — Remove .load-more, add sentinel/spinner CSS"
echo "  public/app.html        — Remove loadMoreBtn, add loadMoreSentinel div"
echo "  public/js/history.js   — Replace click handler with IntersectionObserver"
echo ""
echo -e "${YELLOW}Windows note: On Windows PowerShell, run directly:${NC}"
echo "  npx serve public -p 5000"
echo "  OR: firebase emulators:start"
echo ""
echo "Press Ctrl+C to stop."
wait
